# Generated by Django 5.2.6 on 2025-10-02 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("accepted", "Accepted"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed Delivery"),
                            ("returned", "Returned to Sender"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_person_name", models.CharField(blank=True, max_length=100)),
                ("delivery_person_phone", models.CharField(blank=True, max_length=17)),
                ("pickup_location", models.CharField(blank=True, max_length=200)),
                ("current_location", models.CharField(blank=True, max_length=200)),
                (
                    "estimated_delivery_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("actual_delivery_time", models.DateTimeField(blank=True, null=True)),
                ("pickup_notes", models.TextField(blank=True)),
                ("delivery_notes", models.TextField(blank=True)),
                ("customer_feedback", models.TextField(blank=True)),
                (
                    "delivery_rating",
                    models.IntegerField(
                        blank=True, help_text="1-5 rating from customer", null=True
                    ),
                ),
                ("delivery_issues", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "delivery_time_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "delivery_person_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "product_condition_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("positive_feedback", models.TextField(blank=True)),
                ("improvement_suggestions", models.TextField(blank=True)),
                ("would_recommend", models.BooleanField(null=True)),
                ("delivery_issues", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("business_license", models.CharField(blank=True, max_length=100)),
                (
                    "vehicle_types",
                    models.CharField(
                        help_text="Types of vehicles available", max_length=200
                    ),
                ),
                (
                    "average_delivery_time",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "success_rate",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_location", models.CharField(max_length=200)),
                (
                    "route_sequence",
                    models.JSONField(help_text="Ordered list of delivery stops"),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="Estimated duration in minutes"),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "fuel_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeliverySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (8AM - 12PM)"),
                            ("afternoon", "Afternoon (12PM - 6PM)"),
                            ("evening", "Evening (6PM - 8PM)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("max_deliveries", models.IntegerField(default=10)),
                ("current_bookings", models.IntegerField(default=0)),
                (
                    "additional_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "available_days",
                    models.JSONField(
                        default=list,
                        help_text="List of available days (0=Monday, 6=Sunday)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("order_confirmed", "Order Confirmed"),
                            ("assigned_partner", "Assigned to Delivery Partner"),
                            ("partner_accepted", "Partner Accepted Delivery"),
                            ("pickup_scheduled", "Pickup Scheduled"),
                            ("picked_up_from_farm", "Picked Up from Farm"),
                            ("at_sorting_center", "At Sorting Center"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivery_attempted", "Delivery Attempted"),
                            ("delivered_successfully", "Delivered Successfully"),
                            ("delivery_failed", "Delivery Failed"),
                            ("returned_to_sender", "Returned to Sender"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=22, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=22, null=True
                    ),
                ),
                ("estimated_time", models.DateTimeField(blank=True, null=True)),
                ("actual_time", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Additional tracking data", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "postal_codes",
                    models.TextField(help_text="Comma-separated postal codes"),
                ),
                ("cities", models.TextField(help_text="Comma-separated city names")),
                ("delivery_fee", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "estimated_delivery_hours",
                    models.IntegerField(help_text="Estimated delivery time in hours"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
