# Generated by Django 5.2.6 on 2025-10-02 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryassignment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_assignment",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="deliveryfeedback",
            name="customer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "customer"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliveryfeedback",
            name="delivery_assignment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="delivery.deliveryassignment",
            ),
        ),
        migrations.AddField(
            model_name="deliveryassignment",
            name="delivery_partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="delivery.deliverypartner",
            ),
        ),
        migrations.AddField(
            model_name="deliveryroute",
            name="delivery_partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="delivery.deliverypartner",
            ),
        ),
        migrations.AddField(
            model_name="deliverytracking",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverytracking",
            name="delivery_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking_events",
                to="delivery.deliveryassignment",
            ),
        ),
        migrations.AddField(
            model_name="deliveryslot",
            name="delivery_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_slots",
                to="delivery.deliveryzone",
            ),
        ),
        migrations.AddField(
            model_name="deliveryroute",
            name="delivery_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="delivery.deliveryzone"
            ),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="service_zones",
            field=models.ManyToManyField(
                related_name="delivery_partners", to="delivery.deliveryzone"
            ),
        ),
        migrations.AddField(
            model_name="deliveryassignment",
            name="delivery_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="delivery.deliveryzone"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverytracking",
            index=models.Index(
                fields=["delivery_assignment", "event"],
                name="delivery_de_deliver_a0afa1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverytracking",
            index=models.Index(
                fields=["actual_time"], name="delivery_de_actual__3f60e3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deliveryslot",
            unique_together={("delivery_zone", "slot_type", "start_time")},
        ),
    ]
