# Generated by Django 5.2.6 on 2025-10-02 01:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_customerprofile_farmerprofile_userprofile_and_more"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("sslcommerz_card", "Credit/Debit Card (SSLCommerz)"),
                            ("sslcommerz_bkash", "bKash"),
                            ("sslcommerz_rocket", "Rocket"),
                            ("sslcommerz_nagad", "Nagad"),
                            ("sslcommerz_upay", "Upay"),
                            ("bank_transfer", "Direct Bank Transfer"),
                            ("cash_on_delivery", "Cash on Delivery"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "processing_fee_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "fixed_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                (
                    "maximum_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sslcz_gateway_name",
                    models.CharField(
                        blank=True,
                        help_text="SSLCommerz gateway identifier",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                ("reference_id", models.CharField(blank=True, max_length=100)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("withdrawal", "Withdrawal"),
                            ("commission", "Commission"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gateway_response", models.JSONField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="SSLCommerzTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=255, unique=True)),
                ("gateway_page_url", models.URLField(blank=True)),
                ("val_id", models.CharField(blank=True, max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("card_type", models.CharField(blank=True, max_length=50)),
                (
                    "store_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("card_no", models.CharField(blank=True, max_length=20)),
                ("bank_tran_id", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("tran_date", models.CharField(blank=True, max_length=50)),
                ("error", models.TextField(blank=True)),
                ("currency", models.CharField(default="BDT", max_length=10)),
                ("card_issuer", models.CharField(blank=True, max_length=100)),
                ("card_brand", models.CharField(blank=True, max_length=50)),
                ("card_sub_brand", models.CharField(blank=True, max_length=50)),
                ("card_issuer_country", models.CharField(blank=True, max_length=100)),
                (
                    "card_issuer_country_code",
                    models.CharField(blank=True, max_length=10),
                ),
                ("risk_level", models.CharField(blank=True, max_length=10)),
                ("risk_title", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sslcz_details",
                        to="payments.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmerEarnings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "platform_commission",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("net_earnings", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_paid_out", models.BooleanField(default=False)),
                ("payout_date", models.DateTimeField(blank=True, null=True)),
                ("payout_reference", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to="accounts.farmerprofile",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
            options={
                "unique_together": {("farmer", "order")},
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "status"], name="payments_tr_user_id_b99a80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["order", "status"], name="payments_tr_order_i_028313_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_id"], name="payments_tr_transac_e96a4f_idx"
            ),
        ),
    ]
