# products/management/commands/populate_products.py

import random
from datetime import date, timedelta
from decimal import Decimal

from accounts.models import FarmerProfile, User
from django.core.management.base import BaseCommand
from django.utils.text import slugify
from products.models import Category, Product


class Command(BaseCommand):
    help = "Populate database with 50+ sample product data"

    def handle(self, *args, **kwargs):
        self.stdout.write("Starting data population...")

        # Create categories with images
        categories_data = [
            {
                "name": "Vegetables",
                "description": "Fresh farm vegetables grown with care",
            },
            {
                "name": "Fruits",
                "description": "Seasonal fresh fruits directly from farms",
            },
            {"name": "Dairy Products", "description": "Pure and fresh dairy products"},
            {"name": "Grains & Cereals", "description": "Organic grains and cereals"},
            {
                "name": "Herbs & Spices",
                "description": "Fresh herbs and aromatic spices",
            },
            {
                "name": "Eggs & Poultry",
                "description": "Farm fresh eggs and poultry products",
            },
            {
                "name": "Honey & Bee Products",
                "description": "Pure honey and natural bee products",
            },
            {
                "name": "Organic Products",
                "description": "Certified organic farm products",
            },
        ]

        categories = {}
        for cat_data in categories_data:
            cat, created = Category.objects.get_or_create(
                name=cat_data["name"],
                defaults={"description": cat_data["description"], "is_active": True},
            )
            categories[cat.name] = cat
            if created:
                self.stdout.write(self.style.SUCCESS(f"✓ Created category: {cat.name}"))

        # Get all farmers or create one if none exists
        farmers = list(FarmerProfile.objects.all())
        if not farmers:
            self.stdout.write(self.style.ERROR("❌ No farmer profile found!"))
            self.stdout.write("Please create a farmer user first using:")
            self.stdout.write("python manage.py createsuperuser")
            return

        # Comprehensive products data (50+ products)
        products_data = [
            # Vegetables (15 products)
            {
                "name": "Organic Tomatoes",
                "description": "Fresh organic red tomatoes, vine-ripened and full of flavor. Perfect for salads, cooking, and sauces.",
                "category": "Vegetables",
                "price": 45.00,
                "unit": "kg",
                "stock": 150,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 20,
            },
            {
                "name": "Fresh Potatoes",
                "description": "Farm-fresh potatoes ideal for all cooking needs. Rich in nutrients and taste.",
                "category": "Vegetables",
                "price": 30.00,
                "unit": "kg",
                "stock": 200,
                "organic": False,
                "freshness": "fresh",
                "min_order": 2,
                "max_order": 50,
            },
            {
                "name": "Organic Carrots",
                "description": "Crunchy orange carrots packed with vitamins. Great for juices and cooking.",
                "category": "Vegetables",
                "price": 40.00,
                "unit": "kg",
                "stock": 120,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 15,
            },
            {
                "name": "Fresh Spinach",
                "description": "Leafy green spinach rich in iron and nutrients. Perfect for healthy meals.",
                "category": "Vegetables",
                "price": 35.00,
                "unit": "bunch",
                "stock": 80,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Bell Peppers",
                "description": "Colorful bell peppers - red, yellow, and green. Sweet and crunchy.",
                "category": "Vegetables",
                "price": 60.00,
                "unit": "kg",
                "stock": 90,
                "organic": False,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Fresh Cauliflower",
                "description": "White cauliflower heads perfect for curries and salads.",
                "category": "Vegetables",
                "price": 40.00,
                "unit": "piece",
                "stock": 60,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Green Broccoli",
                "description": "Fresh broccoli florets packed with vitamins and minerals.",
                "category": "Vegetables",
                "price": 80.00,
                "unit": "kg",
                "stock": 50,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 8,
            },
            {
                "name": "Fresh Cucumber",
                "description": "Cool and refreshing cucumbers. Great for salads and snacks.",
                "category": "Vegetables",
                "price": 35.00,
                "unit": "kg",
                "stock": 100,
                "organic": False,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 15,
            },
            {
                "name": "Red Onions",
                "description": "Fresh red onions with strong flavor. Essential kitchen ingredient.",
                "category": "Vegetables",
                "price": 25.00,
                "unit": "kg",
                "stock": 180,
                "organic": False,
                "freshness": "1day",
                "min_order": 2,
                "max_order": 30,
            },
            {
                "name": "Garlic Bulbs",
                "description": "Fresh garlic bulbs with intense flavor. Essential for cooking.",
                "category": "Vegetables",
                "price": 120.00,
                "unit": "kg",
                "stock": 70,
                "organic": True,
                "freshness": "2days",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Fresh Lettuce",
                "description": "Crisp lettuce leaves perfect for fresh salads.",
                "category": "Vegetables",
                "price": 45.00,
                "unit": "piece",
                "stock": 65,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Green Beans",
                "description": "Tender green beans rich in fiber and vitamins.",
                "category": "Vegetables",
                "price": 55.00,
                "unit": "kg",
                "stock": 75,
                "organic": False,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 12,
            },
            {
                "name": "Fresh Cabbage",
                "description": "Green cabbage heads perfect for various dishes.",
                "category": "Vegetables",
                "price": 30.00,
                "unit": "piece",
                "stock": 95,
                "organic": False,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 15,
            },
            {
                "name": "Pumpkin",
                "description": "Fresh pumpkins great for soups and curries.",
                "category": "Vegetables",
                "price": 40.00,
                "unit": "kg",
                "stock": 55,
                "organic": True,
                "freshness": "1day",
                "min_order": 2,
                "max_order": 20,
            },
            {
                "name": "Fresh Radish",
                "description": "Crunchy radishes with a peppery taste.",
                "category": "Vegetables",
                "price": 35.00,
                "unit": "bunch",
                "stock": 60,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 8,
            },
            # Fruits (12 products)
            {
                "name": "Fresh Apples",
                "description": "Crispy red apples grown in our orchards. Sweet and juicy.",
                "category": "Fruits",
                "price": 120.00,
                "unit": "kg",
                "stock": 100,
                "organic": False,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 20,
            },
            {
                "name": "Ripe Bananas",
                "description": "Yellow ripe bananas perfect for eating and smoothies.",
                "category": "Fruits",
                "price": 50.00,
                "unit": "dozen",
                "stock": 85,
                "organic": False,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Organic Mangoes",
                "description": "Sweet and juicy mangoes. The king of fruits.",
                "category": "Fruits",
                "price": 150.00,
                "unit": "kg",
                "stock": 70,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 15,
                "is_seasonal": True,
            },
            {
                "name": "Fresh Oranges",
                "description": "Juicy oranges packed with Vitamin C.",
                "category": "Fruits",
                "price": 80.00,
                "unit": "kg",
                "stock": 120,
                "organic": False,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 20,
            },
            {
                "name": "Fresh Grapes",
                "description": "Sweet green and black grapes. Perfect for snacking.",
                "category": "Fruits",
                "price": 100.00,
                "unit": "kg",
                "stock": 60,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Fresh Strawberries",
                "description": "Juicy red strawberries. Great for desserts.",
                "category": "Fruits",
                "price": 200.00,
                "unit": "pack",
                "stock": 45,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 8,
            },
            {
                "name": "Watermelon",
                "description": "Large sweet watermelons perfect for summer.",
                "category": "Fruits",
                "price": 35.00,
                "unit": "kg",
                "stock": 80,
                "organic": False,
                "freshness": "fresh",
                "min_order": 3,
                "max_order": 30,
                "is_seasonal": True,
            },
            {
                "name": "Fresh Papaya",
                "description": "Ripe papayas rich in vitamins and enzymes.",
                "category": "Fruits",
                "price": 60.00,
                "unit": "kg",
                "stock": 55,
                "organic": False,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 15,
            },
            {
                "name": "Pomegranate",
                "description": "Fresh pomegranates loaded with antioxidants.",
                "category": "Fruits",
                "price": 180.00,
                "unit": "kg",
                "stock": 40,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Fresh Pineapple",
                "description": "Sweet and tangy pineapples. Tropical delight.",
                "category": "Fruits",
                "price": 70.00,
                "unit": "piece",
                "stock": 50,
                "organic": False,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Guava",
                "description": "Fresh guavas with unique flavor and aroma.",
                "category": "Fruits",
                "price": 90.00,
                "unit": "kg",
                "stock": 65,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 12,
            },
            {
                "name": "Fresh Lemon",
                "description": "Tangy lemons perfect for juices and cooking.",
                "category": "Fruits",
                "price": 60.00,
                "unit": "kg",
                "stock": 90,
                "organic": False,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 15,
            },
            # Dairy Products (8 products)
            {
                "name": "Farm Fresh Milk",
                "description": "Pure cow milk from our farm. Fresh and nutritious.",
                "category": "Dairy Products",
                "price": 60.00,
                "unit": "liter",
                "stock": 80,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Fresh Paneer",
                "description": "Homemade cottage cheese. Perfect for curries.",
                "category": "Dairy Products",
                "price": 350.00,
                "unit": "kg",
                "stock": 30,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 5,
            },
            {
                "name": "Fresh Yogurt",
                "description": "Creamy yogurt made from fresh milk. Rich in probiotics.",
                "category": "Dairy Products",
                "price": 70.00,
                "unit": "kg",
                "stock": 50,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 8,
            },
            {
                "name": "Farm Butter",
                "description": "Pure butter churned from fresh cream.",
                "category": "Dairy Products",
                "price": 450.00,
                "unit": "kg",
                "stock": 25,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 5,
            },
            {
                "name": "Fresh Cream",
                "description": "Rich dairy cream for cooking and desserts.",
                "category": "Dairy Products",
                "price": 280.00,
                "unit": "liter",
                "stock": 35,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 5,
            },
            {
                "name": "Ghee (Clarified Butter)",
                "description": "Pure desi ghee made from cow milk.",
                "category": "Dairy Products",
                "price": 550.00,
                "unit": "kg",
                "stock": 40,
                "organic": True,
                "freshness": "1day",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Buttermilk",
                "description": "Refreshing buttermilk, perfect for digestion.",
                "category": "Dairy Products",
                "price": 40.00,
                "unit": "liter",
                "stock": 60,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Cheese Cubes",
                "description": "Farm-made cheese cubes for snacking and cooking.",
                "category": "Dairy Products",
                "price": 400.00,
                "unit": "kg",
                "stock": 20,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 5,
            },
            # Grains & Cereals (8 products)
            {
                "name": "Organic Basmati Rice",
                "description": "Premium quality basmati rice with long grains.",
                "category": "Grains & Cereals",
                "price": 120.00,
                "unit": "kg",
                "stock": 300,
                "organic": True,
                "freshness": "fresh",
                "min_order": 5,
                "max_order": 50,
            },
            {
                "name": "Whole Wheat Flour",
                "description": "Stone-ground whole wheat flour (Atta).",
                "category": "Grains & Cereals",
                "price": 45.00,
                "unit": "kg",
                "stock": 250,
                "organic": True,
                "freshness": "fresh",
                "min_order": 5,
                "max_order": 50,
            },
            {
                "name": "Organic Oats",
                "description": "Rolled oats perfect for healthy breakfast.",
                "category": "Grains & Cereals",
                "price": 150.00,
                "unit": "kg",
                "stock": 100,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 20,
            },
            {
                "name": "Brown Rice",
                "description": "Nutritious brown rice rich in fiber.",
                "category": "Grains & Cereals",
                "price": 90.00,
                "unit": "kg",
                "stock": 150,
                "organic": True,
                "freshness": "fresh",
                "min_order": 2,
                "max_order": 30,
            },
            {
                "name": "Organic Quinoa",
                "description": "Protein-rich quinoa seeds. Superfood grain.",
                "category": "Grains & Cereals",
                "price": 350.00,
                "unit": "kg",
                "stock": 50,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Millet (Bajra)",
                "description": "Nutritious pearl millet for healthy meals.",
                "category": "Grains & Cereals",
                "price": 60.00,
                "unit": "kg",
                "stock": 120,
                "organic": True,
                "freshness": "fresh",
                "min_order": 2,
                "max_order": 30,
            },
            {
                "name": "Corn Flour",
                "description": "Fine corn flour for various recipes.",
                "category": "Grains & Cereals",
                "price": 55.00,
                "unit": "kg",
                "stock": 80,
                "organic": False,
                "freshness": "fresh",
                "min_order": 2,
                "max_order": 20,
            },
            {
                "name": "Red Lentils (Masoor Dal)",
                "description": "High-protein red lentils. Cooks quickly.",
                "category": "Grains & Cereals",
                "price": 110.00,
                "unit": "kg",
                "stock": 140,
                "organic": True,
                "freshness": "fresh",
                "min_order": 2,
                "max_order": 25,
            },
            # Herbs & Spices (5 products)
            {
                "name": "Fresh Coriander",
                "description": "Fresh coriander leaves for garnishing.",
                "category": "Herbs & Spices",
                "price": 20.00,
                "unit": "bunch",
                "stock": 100,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Fresh Mint Leaves",
                "description": "Aromatic mint leaves for chutneys and beverages.",
                "category": "Herbs & Spices",
                "price": 25.00,
                "unit": "bunch",
                "stock": 80,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 8,
            },
            {
                "name": "Fresh Curry Leaves",
                "description": "Aromatic curry leaves essential for Indian cooking.",
                "category": "Herbs & Spices",
                "price": 30.00,
                "unit": "bunch",
                "stock": 70,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Fresh Ginger",
                "description": "Fresh ginger root with strong aroma.",
                "category": "Herbs & Spices",
                "price": 80.00,
                "unit": "kg",
                "stock": 90,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Green Chili",
                "description": "Fresh hot green chilies for spicy dishes.",
                "category": "Herbs & Spices",
                "price": 60.00,
                "unit": "kg",
                "stock": 75,
                "organic": False,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 5,
            },
            # Eggs & Poultry (3 products)
            {
                "name": "Farm Fresh Eggs",
                "description": "Free-range chicken eggs from our farm.",
                "category": "Eggs & Poultry",
                "price": 80.00,
                "unit": "dozen",
                "stock": 150,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 20,
            },
            {
                "name": "Organic Chicken",
                "description": "Free-range organic chicken. Fresh and healthy.",
                "category": "Eggs & Poultry",
                "price": 350.00,
                "unit": "kg",
                "stock": 40,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Duck Eggs",
                "description": "Fresh duck eggs with rich flavor.",
                "category": "Eggs & Poultry",
                "price": 120.00,
                "unit": "dozen",
                "stock": 60,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            # Honey & Bee Products (3 products)
            {
                "name": "Pure Honey",
                "description": "Raw unprocessed honey from our bee farms.",
                "category": "Honey & Bee Products",
                "price": 450.00,
                "unit": "kg",
                "stock": 70,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Organic Beeswax",
                "description": "Pure beeswax for various uses.",
                "category": "Honey & Bee Products",
                "price": 600.00,
                "unit": "kg",
                "stock": 30,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 5,
            },
            {
                "name": "Bee Pollen",
                "description": "Natural bee pollen packed with nutrients.",
                "category": "Honey & Bee Products",
                "price": 800.00,
                "unit": "kg",
                "stock": 20,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 3,
            },
            # Organic Products (3 products)
            {
                "name": "Organic Mushrooms",
                "description": "Fresh organic mushrooms grown in controlled environment.",
                "category": "Organic Products",
                "price": 200.00,
                "unit": "kg",
                "stock": 45,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
            {
                "name": "Organic Tofu",
                "description": "Fresh organic tofu made from soybeans.",
                "category": "Organic Products",
                "price": 180.00,
                "unit": "kg",
                "stock": 35,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 8,
            },
            {
                "name": "Organic Sprouts Mix",
                "description": "Fresh mixed sprouts - healthy and nutritious.",
                "category": "Organic Products",
                "price": 90.00,
                "unit": "kg",
                "stock": 50,
                "organic": True,
                "freshness": "fresh",
                "min_order": 1,
                "max_order": 10,
            },
        ]

        # Create products
        created_count = 0
        for prod_data in products_data:
            # Get category
            category = categories.get(prod_data["category"])
            if not category:
                continue

            # Randomly assign to a farmer
            farmer = random.choice(farmers)

            # Calculate dates
            harvest_date = date.today() - timedelta(days=random.randint(0, 3))

            # Check if product already exists
            existing = Product.objects.filter(
                name=prod_data["name"], farmer=farmer
            ).first()

            if existing:
                self.stdout.write(
                    self.style.WARNING(f'⚠ Product already exists: {prod_data["name"]}')
                )
                continue

            # Create product
            product = Product.objects.create(
                farmer=farmer,
                category=category,
                name=prod_data["name"],
                description=prod_data["description"],
                price_per_unit=Decimal(str(prod_data["price"])),
                unit=prod_data["unit"],
                stock_quantity=prod_data["stock"],
                minimum_order_quantity=prod_data.get("min_order", 1),
                maximum_order_quantity=prod_data.get("max_order", None),
                freshness=prod_data.get("freshness", "fresh"),
                organic=prod_data.get("organic", False),
                harvest_date=harvest_date,
                is_available=True,
                is_seasonal=prod_data.get("is_seasonal", False),
                rating=Decimal(str(random.uniform(3.5, 5.0))),
                review_count=random.randint(5, 50),
                total_sold=random.randint(10, 200),
            )

            created_count += 1
            self.stdout.write(
                self.style.SUCCESS(
                    f"✓ Created product: {product.name} ({product.category.name})"
                )
            )

        # Summary
        self.stdout.write(self.style.SUCCESS("=" * 60))
        self.stdout.write(
            self.style.SUCCESS(f"🎉 Data population completed successfully!")
        )
        self.stdout.write(
            self.style.SUCCESS(f"📦 Total products created: {created_count}")
        )
        self.stdout.write(self.style.SUCCESS(f"📂 Total categories: {len(categories)}"))
        self.stdout.write(self.style.SUCCESS(f"👨‍🌾 Using {len(farmers)} farmer(s)"))
        self.stdout.write(self.style.SUCCESS("=" * 60))
